export const skillNames = {
	woodcutting: 'woodcutting',
	fishing: 'fishing',
	firemaking: 'firemaking',
	cooking: 'cooking',
	mining: 'mining',
	smithing: 'smithing',
	attack: 'attack',
	strength: 'strength',
	defence: 'defence',
	hitpoints: 'hitpoints',
	thieving: 'thieving',
	farming: 'farming',
	ranged: 'ranged',
	fletching: 'fletching',
	crafting: 'crafting',
	runecrafting: 'runecrafting',
	magic: 'magic',
	prayer: 'prayer',
	slayer: 'slayer',
	herblore: 'herblore',
	agility: 'agility',
	summoning: 'summoning',
	astrology: 'astrology',
}

export const skillList = [
	skillNames.woodcutting,
	skillNames.fishing,
	skillNames.firemaking,
	skillNames.cooking,
	skillNames.mining,
	skillNames.smithing,
	skillNames.attack,
	skillNames.strength,
	skillNames.defence,
	skillNames.hitpoints,
	skillNames.thieving,
	skillNames.farming,
	skillNames.ranged,
	skillNames.fletching,
	skillNames.crafting,
	skillNames.runecrafting,
	skillNames.magic,
	skillNames.prayer,
	skillNames.slayer,
	skillNames.herblore,
	skillNames.agility,
	skillNames.summoning,
	skillNames.astrology,
]
